module.exports = ($) => [
  [$._value_type],
  [$._type2],
  [$._type1, $.constructor],
  [$._literal, $._expression],
  [$._literal, $._literal_pattern],
  [$.literal_list, $.literal_list_pattern],
  [$._pattern_rhs, $._boolean_exp],
  [$._hq_qualified_wordy_id, $._wordy_definition_name],
  [$._literal, $._term_leaf],
  [$._expression, $._term_leaf],
  [$._expression, $._keyword_block],
  [$._literal_pattern, $._number],
  [$._literal, $._number],
  [$._literal, $._link],
  [$._infix_app_or_boolean_op],
  [$._pattern_constructor, $.effect_bind],
  [$._identifier, $._wordy_definition_name],
  [$.literal_function, $._prefix_lhs],
  [$.literal_function, $._infix_lhs],
]
