module.exports = $ => [
  [$._value_type],
  [$._type2],
  [$._type1, $.constructor],
  [$._literal, $._expression],
  [$._literal, $._literal_pattern],
  [$.literal_list, $.literal_list_pattern],
  [$._pattern_rhs, $._boolean_exp],
  [$._hq_qualified_wordy_id, $._wordy_definition_name],
  [$._literal, $._term_leaf],
  [$._expression, $._term_leaf],
  [$._expression, $._keyword_block],
  [$._literal_pattern, $._number],
  [$._literal, $._number],
  [$._literal, $._link],
  [$._infix_app_or_boolean_op],
  [$._identifier, $._wordy_definition_name],
  [$.literal_function, $._prefix_lhs],
  [$.literal_function, $._infix_lhs],
  [$.var_or_nullary_ctor, $._pattern_constructor],
  [$._term_leaf, $._watch_expression],
  [$._literal_pattern, $._term_leaf],
  [$._pattern_constructor, $._term_leaf],
  [$.var_or_nullary_ctor, $._term_leaf],
  [$.wordy_id, $._hq_qualified_wordy_id],
  [$.else_block],
  [$._statement, $.else_block],
  [$._pattern_root],
  [$.tuple_or_parenthesized, $.parenthesized_or_tuple_pattern],
  // [$.delay_block],
  // [$._statement, $.]
  [$.destructuring_bind],
  [$._rewrite_term_like],
]
