module.exports = ($) => [
  [$._value_type],
  [$._type2],
  [$._type1, $.constructor],
  // [$._prefix_function_application, $.function_application],
  [$._literal, $._expression],
  // [$._infix_op_application, $.literal_function],
  // [$.imm_symboly_id, $._op],
  [$._literal, $._literal_pattern],
  // [$._expression, $.constructor_or_variable_pattern],
  [$.literal_list, $.literal_list_pattern],
  [$._identifier, $._wordy_definition_name, $.literal_function],
  [$._identifier, $._wordy_definition_name],
  [$._wordy_definition_name, $.literal_function],
  [$._identifier, $._wordy_definition_name, $.literal_function, $._lhs],
  [$._identifier, $._symboly_definition_name],
  // [$._symboly_definition_name, $._op],
  [$._identifier, $.literal_function],
  [$._pattern_rhs, $._boolean_exp],
  // [$._pattern_rhs, $._infix_op_application],
  [$._hq_qualified_wordy_id, $._pattern_leaf],
  [$._identifier, $._hq_qualified_wordy_id, $._pattern_leaf],
  [$._hq_qualified_wordy_id, $._wordy_definition_name],
  [$._hq_qualified_wordy_id, $._wordy_definition_name, $.literal_function],
  [$._identifier, $._hq_qualified_wordy_id],
  [$._hq_qualified_symboly_id, $._symboly_definition_name],
  [$._identifier, $._hq_qualified_symboly_id, $._symboly_definition_name],
  [$._identifier, $._hq_qualified_symboly_id],
  [$._identifier, $._pattern_leaf],
  [$.exp_let, $._statement],
  [$._identifier, $._wordy_definition_name, $.literal_function, $._prefix_lhs],
  [$._literal, $._term_leaf],
  [$._expression, $._term_leaf],
  [$._expression, $._keyword_block],
  [$._literal_pattern, $._term_leaf],
  // [$.constructor_or_variable_pattern, $._term_leaf],
  [$._identifier, $._wordy_definition_name, $._prefix_lhs],
  [$.literal_function2, $._term],
  // [$.tuple_or_parenthesized, $.tuple_pattern],
  [$._identifier, $._hq_qualified_wordy_id, $._wordy_definition_name],
  [$._identifier, $._prefix_lhs],
  [$._literal_pattern, $._number],
  // [$.literal_list_pattern, $._term_list],
  // [$.ctor, $._term_leaf],
  [$._literal, $._number],
  [$._literal, $._link],
  [$.destructuring_bind],
  // [$.literal_list, $._term_list],
  [$._term4, $._hq_qualified_wordy_id],
];
