module.exports = {
  do: (_) => "do",
  kw_let: (_) => "let",
  type_kw: ($) => "type",
  pipe: ($) => "|",
  match: ($) => "match",
  cases: ($) => "cases",
  otherwise: ($) => "otherwise",
  as: ($) => "@",
  structural: ($) => "structural",
  unique: ($) => "unique",
  ability: ($) => "ability",
  where: ($) => "where",
  or: ($) => "||",
  and: ($) => "&&",
  kw_forall: ($) => choice("forall", "∀"),
  kw_equals: ($) => "=",
  type_signature_colon: ($) => ":",
  kw_termlink: ($) => "termLink",
  kw_typelink: ($) => "typeLink",
  handle: ($) => "handle",
  with: ($) => "with",
  open_parens: $ => prec.right('('),
  close_parens: $ => ')',
};
