name: ci
on:
  push:
    branches: [ci-test]
    # paths:
      # - src/grammar.json
      # - package.json
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run parser and binding tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{runner.os == 'Linux'}}
          test-swift: ${{runner.os == 'macOS'}}
      - name: Parse sample files
        uses: tree-sitter/parse-action@v4
        id: parse-files
        with:
          files: examples/**
      - name: Upload failures artifact
        uses: actions/upload-artifact@v4
        if: "!cancelled() && steps.parse-files.outcome == 'failure'"
        with:
          name: failures-${{runner.os}}
          path: ${{steps.parse-files.outputs.failures}}
  # npm:
  #   uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
  #   secrets:
  #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
# inputs:
#   package-name:
#     description: The name of the package
#     default: ${{github.event.repository.name}}
#     type: string
#   environment-name:
#     description: The name of the environment
#     default: npm
#     type: string
#   node-version:
#     description: The NodeJS version
#     default: ${{vars.NODE_VERSION || 'latest'}}
#     type: string
#   secrets:
#     NODE_AUTH_TOKEN:
#       description: The authentication token for npm
#       required: true

