name: Regenerate parser

on:
  push:
    branches: ["*"]
  pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true


jobs:
  regenerate:
    uses: kylegoetz/workflows/.github/workflows/regenerate.yml@main
    if: github.actor == 'dependabot[bot]'  
